# Python Assignment - 2 

## Types of Inheritance in Python.

### 1). Single Inheritance.

In [1]:
class parent:
    def function_1(self):
        print("The funciton is in Parent class.")
class children(parent):
    def function_2(self):
        print("The function is in Child class.")
obj = children()
obj.function_1()
obj.function_2()

The funciton is in Parent class.
The function is in Child class.


### 2). Multiple Inheritance.

In [7]:
class Mother:
    mothername = ""
 
    def mother(self):
        print(self.mothername)
 
 
class Father:
    fathername = ""
 
    def father(self):
        print(self.fathername)
 
 
class Son(Mother, Father):
    def parents(self):
        print("Father's Name:", self.fathername)
        print("Mother's Name:", self.mothername)
 
 
s1 = Son()
s1.fathername = "Ramesh"
s1.mothername = "Vanitha"
s1.parents()

Father's Name: Ramesh
Mother's Name: Vanitha


### 3). Multi-Level Inheritance.

In [11]:
class Grandfather:
 
    def __init__(self, grandfathername):
        self.grandfathername = grandfathername
 
 
class Father(Grandfather):
    def __init__(self, fathername, grandfathername):
        self.fathername = fathername

        Grandfather.__init__(self, grandfathername)
 
class Son(Father):
    def __init__(self, sonname, fathername, grandfathername):
        self.sonname = sonname
 
        
        Father.__init__(self, fathername, grandfathername)
 
    def print_name(self):
        print("Grandfather's name :", self.grandfathername)
        print("Father's name :", self.fathername)
        print("Son's name :", self.sonname)
 
 

s1 = Son('Hirutik', 'Ramesh', 'Ramachandran')
print(s1.grandfathername)
s1.print_name()

Ramachandran
Grandfather's name : Ramachandran
Father's name : Ramesh
Son's name : Hirutik


### 4). Hierarchical Inheritance.

In [12]:
class Parent:
    def func1(self):
        print("The function is in Parent class.")
 
 
class Child1(Parent):
    def func2(self):
        print("The function is in Second Child.")
 
 
class Child2(Parent):
    def func3(self):
        print("The function is in First Child.")
 
object1 = Child1()
object2 = Child2()
object1.func1()
object1.func2()
object2.func1()
object2.func3()

The function is in Parent class.
The function is in Second Child.
The function is in Parent class.
The function is in First Child.


### 5). Hybrid Inheritance.

In [13]:
class School:
    def func1(self):
        print("The function is in College.")
 
 
class Student1(School):
    def func2(self):
        print("The function is in Student 1. ")
 
 
class Student2(School):
    def func3(self):
        print("The function is in Student 2.")
 
 
class Student3(Student1, School):
    def func4(self):
        print("The function is in Student 3.")
 
object = Student3()
object.func1()
object.func2()

The function is in College.
The function is in Student 1. 


## Exception Handling in Python.

### 1). ZeroDivisionError.

In [15]:
marks = 10000
try:
    a = marks / 0 
    print(a)
except:
    print ("ERROR OCCURRED !!!")
    print(marks)

ERROR OCCURRED !!!
10000


### 2). Unexpected Indent

In [18]:
a = [1, 2, 3]
try: 
    print ("Third element = %d" %(a[1]))
    print ("Fourth element = %d" %(a[3]))
except:
    print ("ERROR OCCURRED !!!")

Third element = 2
ERROR OCCURRED !!!


### 3). Value Error.

In [24]:
while True:
    try:
        x = int(input("Please Enter a Number: "))
        break
    except ValueError:
            print("INVALID NUMBER!! TRY AGAIN")

Please enter a number: Two
INVALID NUMBER!! TRY AGAIN
Please enter a number: 2


### 4). File Opening Error.

In [35]:
try:
    f = open("demofile.txt")
    try:
        f.write("Lorum Ipsum")
    except:
        print("SOMETHING WENT WRONG!! FILE NOT OPENING.")
    finally:
        f.close()
except:           
        print("SOMETHING WENT WRONG!! FILE NOT OPENING.")

SOMETHING WENT WRONG!! FILE NOT OPENING.


### 5). IndentationError.

In [42]:
a = 10
try:
     b = 19
     c = a+b
except:
    print("INDENTATION ERROR!! PLEASE CORRECT IT")
print(c)


29


### 6). Name Error.

In [44]:
try:
    print(s)
except NameError:
    print("Variable s is not defined properly")
except:
    print("Something else went wrong")

Variable s is not defined properly


## Regular Expression in Python.

### Findall()

In [45]:
import re

word = "No Pain No Gain"
x = re.findall("ai", word)
print(x)

['ai', 'ai']


### Search()

In [51]:
import re

par = "I Love Python"
x = re.search("\s", par)
print("The located in position:", x.start())

The located in position: 1


### Split()

In [53]:
import re
sen = "My Name is Hirutik"
x = re.split("\s", sen)
print(x)

['My', 'Name', 'is', 'Hirutik']


### Sub()

In [59]:
import re
part = "Hirutik B.Teck AI&DS"
x = re.sub("\s", "/", part)
print(x)

Hirutik/B.Teck/AI&DS


## Aggregate Functions in Python.

### Largest Elements of two Arrays.

In [60]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1
b = np.array([2,3,4,6,7])
print(b)

[2 3 4 6 7]


### 2-Dimensional Arrays.

In [61]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Sum Function.

In [63]:
ar1=np.array([21,45,87,34,90,4,23,65])
ar1.sum()

369

### Sum of Columns.

In [65]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2.sum(axis = 0)

array([12, 15, 18])

### Sum of Rows.

In [66]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2.sum(axis = 1)

array([ 6, 15, 24])

### Product Function.

In [68]:
arr1 = np.array([1,2,3,4,5])
np.prod(arr1)

120

### Product of Columns.

In [69]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.product(arr2,axis = 0)

array([ 28,  80, 162])

### Product of Rows.

In [70]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.prod(arr2,axis = 1)

array([  6, 120, 504])

### Average Function.

In [71]:
arr1 = np.array([1,2,3,4,5])
np.average(arr1)

3.0

### Average of Columns.

In [73]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.average(arr2,axis =0)

array([4., 5., 6.])

### Average of Rows.

In [74]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.average(arr2,axis = 1)

array([2., 5., 8.])

### Minimum Function.

In [76]:
arr1 = np.array([1,2,3,4,5])
arr1.min()

1

### Minimum Of Columns.

In [77]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2.min(axis = 0)

array([1, 2, 3])

### Minimum of Rows.

In [79]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2.min(axis = 1)

array([1, 4, 7])

### Minimum of two matrices.

In [82]:
import numpy as np
x = np.random.randint(1, 10, size = (3,3))
print(x)
print()
 
y = np.random.randint(1, 10, size = (3,3))
print(y)
 
print('\nTHE MINIMUM MATRIX:')
print(np.minimum(x, y))

[[4 5 6]
 [7 2 3]
 [9 9 3]]

[[8 6 2]
 [6 7 7]
 [8 9 5]]

THE MINIMUM MATRIX:
[[4 5 2]
 [6 2 3]
 [8 9 3]]


### Maximum of two matrices.

In [83]:
import numpy as np
x = np.random.randint(1, 10, size = (3,3))
print(x)
print()
 
y = np.random.randint(1, 10, size = (3,3))
print(y)
 
print('\nTHE MAXIMUM MATRIX:')
print(np.maximum(x, y))

[[8 9 5]
 [7 5 1]
 [2 4 9]]

[[4 2 5]
 [4 8 3]
 [3 6 1]]

THE MAXIMUM MATRIX:
[[8 9 5]
 [7 8 3]
 [3 6 9]]


### Mean Function.

In [85]:
arr1 = np.array([1,2,3,4,5])
np.mean(arr1)

3.0

In [86]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.mean(arr2)

5.0

### Median Function.

In [87]:
arr1 = np.array([1,2,3,4,5])
np.median(arr1)

3.0

In [88]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.median(arr2)

5.0

### Median of Columns.

In [89]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.median(arr2, axis = 0)

array([4., 5., 6.])

### Median of Rows.

In [90]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.median(arr2, axis = 1)

array([2., 5., 8.])

### Variance Function.

In [91]:
arr1 = np.array([1,2,3,4,5])
arr1.var()

2.0

In [92]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2.var()

6.666666666666667